### ISSUE TITLE
A possibility to rename BuildConfig

### ISSUE THREAD

**Issue by arteme** [mfuerstenau/gradle-buildconfig-plugin#1]
It would be nice to be able to override the name of the generated class "BuildConfig" to something user-defined.

**Comment by mfuerstenau** [comment]
I will look into this.

**Comment by mfuerstenau** [comment]
Sorry for the long waiting time. I pushed 1.0.6 to the plugins portal, it's based on the groovy branch.There's the {{clsName}} property to the extension which can hold a custom name.

``` groovy
buildConfig {
    sourceSets {
        main {
            packageName = 'de.fuerstenau.buildconfig.sample'
            clsName = 'WowBuildConfigWithCustomName'
            buildConfigField "boolean", "IS_DEBUG", "true"
        }
    }
}
```

**Comment by arteme** [comment]
Great, thank you!

**Comment by mfuerstenau** [comment]
new version is up, more configuration options, better readme
