### ISSUE TITLE
Does this work with Retrolambda?

### ISSUE THREAD

**Issue by ZakTaccardi** [mfuerstenau/gradle-buildconfig-plugin#4]
Getting an error when I try to access the BuildConfig class during runtime. `server/BuildConfig : Unsupported major.minor version 52.0`

**Comment by mfuerstenau** [comment]
Yeah, I made the mistake and put the binaries compiled with Java 8 up. :-( I will fix this today and put up a binary compiled with Java 7. If you can switch to Java 8 it would also work. But I know that this sometimes is not possible.

**Comment by ZakTaccardi** [comment]
thanks! This is a java module I'm including in an Android build, so java 7 is needed. I appreciate the quick response!

**Comment by akoscz** [comment]
@ZakTaccardi for what it's worth,  the `buildConfigField` method is already part of the [Android Gradle DSL](https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.BuildType.html). In other words, generating a `BuildConfig.java` file at build time is baked into the Android gradle build tools.

**Comment by mfuerstenau** [comment]
@ZakTaccardi Published 1.1.3. Only difference is that it's compiled with OpenJDK7u80. Also added a badge to download binary automatically build from tag from bintray.

**Comment by danelyan** [comment]
@akoscz if you want generate some params for java library (not android). 
For example, [domain layer in Clean Architecture](https://github.com/android10/Android-CleanArchitecture/tree/master/domain ) should be android independent.
