### ISSUE TITLE
appVersion in buildConfig yields error

### ISSUE THREAD

**Issue by raleighr3** [mfuerstenau/gradle-buildconfig-plugin#8]
When trying to set the appVersion in buildConfig gradle gives the following error:

```
* What went wrong:
A problem occurred evaluating project ':tools:DebugInspector'.
> Could not set unknown property 'appVersion' for object of type de.fuerstenau.gradle.buildconfig.BuildConfigExtension.
```

If I try just `version` then it seems to work if set to a constant.  Doesn't work when set `project.version`.

This is in a subproject build of multi-project gradle setup.

**Comment by mfuerstenau** [comment]
@raleighr3 You are right. Seems to be a _documentation error_ on my part, it's `version` not ~~`appVersion`~~ as documented. Try

``` gradle
buildConfig {
   version = 'whatever you want'
}
```

also: if version is not set explicitely, it defaults to `project.version`. so

``` gradle
buildConfig {

}
```

would have the same effect as:

``` gradle
buildConfig {
   ...
   version = project.version
}
```

**Comment by mfuerstenau** [comment]
I corrected the README.md. I will close this issue. Feel free to reopen if there's still a problem.
