### ISSUE TITLE
Plugin creates 2 BuildConfig files

### ISSUE THREAD

**Issue by Pirksy** [mfuerstenau/gradle-buildconfig-plugin#9]
Hello, i'm using  '1.1.7' plugin. I want to move BuildConfig to another package using 
`buildConfig {
  buildConfigField 'String', 'LIBRARY_NAME', 'java'
  packageName = 'com.io.lib.debug'
}`
, but plugin creates two files - 'com.io.lib.debug' and 'com.io.lib'. How can I resolve this?
Sorry for english

**Comment by mfuerstenau** [comment]
Can you give a little more detail. I guess `com.io.lib` is your your artifact group? Did you do a `clean build` or just a `build` (maybe there are some remains from previous builds)?

**Comment by Pirksy** [comment]
clean build helped, thank you
